# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: FymKNr3c0ORUoKrVMwR0h4STeRgGRH5X
            client-secret: A5MiW9Howz2itGE1zVRxxJ98_pbmVsx2njAmP2CCqsvPYdHptJFl3TLmQQhAtLYj
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://maaikedupont.eu.auth0.com/